# Generated by Django 2.0.7 on 2018-07-27 04:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('filmid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pic', models.CharField(max_length=30, verbose_name='pic')),
                ('pic_url', models.CharField(max_length=30, verbose_name='pic_url')),
                ('rs232_time', models.DateTimeField(blank=True, null=True, verbose_name='rs232 time')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='FilmGap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap0', models.FloatField(blank=True, null=True, verbose_name='左邊|粉色')),
                ('gap1', models.FloatField(blank=True, null=True, verbose_name='粉色|橘色')),
                ('gap2', models.FloatField(blank=True, null=True, verbose_name='橘色|黃色')),
                ('gap3', models.FloatField(blank=True, null=True, verbose_name='黃色|綠色')),
                ('gap4', models.FloatField(blank=True, null=True, verbose_name='綠色|藍色')),
                ('gap5', models.FloatField(blank=True, null=True, verbose_name='藍色|右邊')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film_gap', to='films.Film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'FilmGap',
                'verbose_name_plural': 'FilmGaps',
            },
        ),
        migrations.CreateModel(
            name='FilmLen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pink', models.FloatField(blank=True, null=True, verbose_name='粉色')),
                ('orange', models.FloatField(blank=True, null=True, verbose_name='橘色')),
                ('yellow', models.FloatField(blank=True, null=True, verbose_name='黃色')),
                ('green', models.FloatField(blank=True, null=True, verbose_name='綠色')),
                ('blue', models.FloatField(blank=True, null=True, verbose_name='藍色')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film_len', to='films.Film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'FilmLen',
                'verbose_name_plural': 'FilmLens',
            },
        ),
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20, verbose_name='content_type')),
            ],
            options={
                'verbose_name': 'FilmType',
                'verbose_name_plural': 'FilmTypes',
            },
        ),
        migrations.CreateModel(
            name='FilmWidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pink', models.FloatField(blank=True, null=True, verbose_name='粉色')),
                ('orange', models.FloatField(blank=True, null=True, verbose_name='橘色')),
                ('yellow', models.FloatField(blank=True, null=True, verbose_name='黃色')),
                ('green', models.FloatField(blank=True, null=True, verbose_name='綠色')),
                ('blue', models.FloatField(blank=True, null=True, verbose_name='藍色')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film_width', to='films.Film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'FilmWidth',
                'verbose_name_plural': 'FilmWidths',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_types', to='films.FilmType', verbose_name='FilmType'),
        ),
    ]
