# Generated by Django 2.0.7 on 2018-07-30 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20180727_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'FilmSeq',
                'verbose_name_plural': 'FilmSeqs',
                'ordering': ('create_time',),
            },
        ),
        migrations.AlterField(
            model_name='filmgap',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film_gaps', to='films.Film', verbose_name='FilmGaps'),
        ),
    ]
