# Generated by Django 2.0.7 on 2018-07-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20180731_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gap_ret',
            field=models.CharField(choices=[('0', 'PASS'), ('1', 'FAIL')], max_length=4, verbose_name='長度檢驗'),
        ),
        migrations.AlterField(
            model_name='film',
            name='len_ret',
            field=models.CharField(choices=[('0', 'PASS'), ('1', 'FAIL')], max_length=4, verbose_name='間距檢驗'),
        ),
    ]
