# Generated by Django 2.0.7 on 2018-08-01 02:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='seq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='film_seqs', to='films.FilmSeq', verbose_name='FilmSeqs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='cam',
            field=models.IntegerField(choices=[(0, 'CAM0'), (1, 'CAM1')], verbose_name='CAM NO.'),
        ),
        migrations.AlterField(
            model_name='film',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='filmseq',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='filmseq',
            name='seqid',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
