# Generated by Django 2.1 on 2018-09-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_auto_20180816_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rs232_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rs232_time'),
        ),
    ]
