# Generated by Django 2.0.7 on 2018-07-06 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180705_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap0', models.FloatField(blank=True, null=True, verbose_name='左邊|粉色')),
                ('gap1', models.FloatField(blank=True, null=True, verbose_name='粉色|橘色')),
                ('gap2', models.FloatField(blank=True, null=True, verbose_name='橘色|黃色')),
                ('gap3', models.FloatField(blank=True, null=True, verbose_name='黃色|綠色')),
                ('gap4', models.FloatField(blank=True, null=True, verbose_name='綠色|藍色')),
                ('gap5', models.FloatField(blank=True, null=True, verbose_name='藍色|右邊')),
                ('pink', models.FloatField(blank=True, null=True, verbose_name='粉色')),
                ('orange', models.FloatField(blank=True, null=True, verbose_name='橘色')),
                ('yellow', models.FloatField(blank=True, null=True, verbose_name='黃色')),
                ('green', models.FloatField(blank=True, null=True, verbose_name='綠色')),
                ('blue', models.FloatField(blank=True, null=True, verbose_name='藍色')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
