# Generated by Django 2.0.7 on 2018-07-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_filmparameter_rs232_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmparameter',
            options={'ordering': ('create_time',), 'verbose_name': 'FilmParameter', 'verbose_name_plural': 'FilmParameters'},
        ),
    ]
