# Generated by Django 2.1.1 on 2018-09-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180910_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarecord',
            name='device',
        ),
        migrations.DeleteModel(
            name='FilmParameter',
        ),
        migrations.DeleteModel(
            name='TemperatureRecord',
        ),
        migrations.DeleteModel(
            name='DataRecord',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
