# Generated by Django 2.1.1 on 2018-09-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-create_time',), 'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='filmseq',
            options={'ordering': ('-create_time',), 'verbose_name': 'FilmSeq', 'verbose_name_plural': 'FilmSeqs'},
        ),
    ]
