# Generated by Django 2.1 on 2019-01-28 09:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20180928_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='sv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='film',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sv'], name='films_film_sv_63e1cd_gin'),
        ),
    ]
