# Generated by Django 2.0.7 on 2018-07-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20180727_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmgap',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='pic_url',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='pic_url'),
        ),
        migrations.AlterField(
            model_name='filmgap',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film_gap', to='films.Film', verbose_name='Film'),
        ),
    ]
