# Generated by Django 2.1 on 2019-01-29 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20190129_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmseq',
            name='seqid',
            field=models.UUIDField(db_index=True, default=uuid.uuid1),
        ),
    ]
