# Generated by Django 2.1 on 2019-01-29 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20190129_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
