# Generated by Django 2.1 on 2019-01-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20190129_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pic',
            field=models.CharField(db_index=True, max_length=30, verbose_name='pic'),
        ),
    ]
